---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-cr
spec:
  limits:
    cpu: 10
    memory: 20Gi
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-family
        minValues: 1
        operator: In
        values:
        - c5a
        - c6a
        - c7i-flex
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
---          
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 
  role: "hoge-role"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "hoge"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "hoge"
